=begin
#DealMaker API

#Welcome to the DealMaker API.  # Introduction  This is a test introduction.  # Usage  This is a usage example.  # Support  For more support, contact [email].

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for DealMakerAPI::DealApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DealApi' do
  before do
    # run before each test
    @api_instance = DealMakerAPI::DealApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DealApi' do
    it 'should create an instance of DealApi' do
      expect(@api_instance).to be_instance_of(DealMakerAPI::DealApi)
    end
  end

  # unit tests for get_deals_id
  # Get a deal by id
  # Get a deal
  # @param id The deal id.
  # @param [Hash] opts the optional parameters
  # @return [V1EntitiesDeal]
  describe 'get_deals_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
