=begin
#DealMaker API

#Welcome to the DealMaker API.  # Introduction  This is a test introduction.  # Usage  This is a usage example.  # Support  For more support, contact [email].

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

module DealMakerAPI
  VERSION = '0.0.1'
end
