=begin
#DealMaker API

#Welcome to the DealMaker API.  # Introduction  This is a test introduction.  # Usage  This is a usage example.  # Support  For more support, contact [email].

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DealMakerAPI::V1EntitiesDeal
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DealMakerAPI::V1EntitiesDeal do
  let(:instance) { DealMakerAPI::V1EntitiesDeal.new }

  describe 'test an instance of V1EntitiesDeal' do
    it 'should create an instance of V1EntitiesDeal' do
      expect(instance).to be_instance_of(DealMakerAPI::V1EntitiesDeal)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
