# -*- encoding: utf-8 -*-

=begin
#DealMaker API

#Welcome to the DealMaker API.  # Introduction  This is a test introduction.  # Usage  This is a usage example.  # Support  For more support, contact [email].

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "DealMakerAPI/version"

Gem::Specification.new do |s|
  s.name        = "DealMakerAPI"
  s.version     = DealMakerAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["DealMaker"]
  s.email       = ["api@dealmaker.tech"]
  s.homepage    = "https://dealmaker.tech"
  s.summary     = "A ruby wrapper for the DealMaker API"
  s.description = "A ruby wrapper for the DealMaker API"
  s.license     = "TODO"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
