=begin
#DealMaker API

#Welcome to the DealMaker API.  # Introduction  This is a test introduction.  # Usage  This is a usage example.  # Support  For more support, contact [email].

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

# Common files
require 'DealMakerAPI/api_client'
require 'DealMakerAPI/api_error'
require 'DealMakerAPI/version'
require 'DealMakerAPI/configuration'

# Models
require 'DealMakerAPI/models/v1_entities_deal'

# APIs
require 'DealMakerAPI/api/deal_api'

module DealMakerAPI
  class << self
    # Customize default settings for the SDK using block.
    #   DealMakerAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
