/**
 * DealMaker API
 * Welcome to the DealMaker API.  # Introduction  This is a test introduction.  # Usage  This is a usage example.  # Support  For more support, contact [email].
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import V1EntitiesDeal from './model/V1EntitiesDeal';
import DealApi from './api/DealApi';


/**
* A javascript wrapper for the DealMaker API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Dealmakerapi = require('index'); // See note below*.
* var xxxSvc = new Dealmakerapi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Dealmakerapi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Dealmakerapi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Dealmakerapi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The V1EntitiesDeal model constructor.
     * @property {module:model/V1EntitiesDeal}
     */
    V1EntitiesDeal,

    /**
    * The DealApi service constructor.
    * @property {module:api/DealApi}
    */
    DealApi
};
