name: Publish

on:
  push:
    branches: [ main ]

jobs:
  javascript:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: v1/clients/javascript

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
  ruby:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Setup gem credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBY_GEMS_API_KEY}\n" > $HOME/.gem/credentials
        env:
          RUBY_GEMS_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
      - name: Build gem
        run: gem build -C v1/clients/ruby
      - name: Publish gem
        run: gem push v1/clients/ruby/DealMakerAPI-*.gem